spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/shop?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 127.0.0.1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml